-- phpMyAdmin SQL Dump
-- version 4.9.1
-- https://www.phpmyadmin.net/
--
-- Host: localhost
-- Generation Time: Jun 16, 2022 at 10:00 AM
-- Server version: 10.5.9-MariaDB-log
-- PHP Version: 7.3.27

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET AUTOCOMMIT = 0;
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `ca_uic`
--

-- --------------------------------------------------------

--
-- Table structure for table `terms`
--

CREATE TABLE `terms` (
  `id` bigint(20) UNSIGNED NOT NULL,
  `name` varchar(191) COLLATE utf8_unicode_ci NOT NULL,
  `description` text COLLATE utf8_unicode_ci NOT NULL,
  `is_deleted` int(11) NOT NULL DEFAULT 0,
  `created_user` int(11) NOT NULL,
  `updated_user` int(11) NOT NULL,
  `deleted_at` timestamp NULL DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  `description_en` text COLLATE utf8_unicode_ci DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

--
-- Dumping data for table `terms`
--

INSERT INTO `terms` (`id`, `name`, `description`, `is_deleted`, `created_user`, `updated_user`, `deleted_at`, `created_at`, `updated_at`, `description_en`) VALUES
(1, '2.1', '<span style=\"font-size: 11.0pt; line-height: 115%; font-family: \'Cambria\',serif;\">H&agrave;nh động cố &yacute; của người được bảo hiểm hoặc người được thừa kế hợp ph&aacute;p.</span>', 0, 16, 16, NULL, '2022-04-25 07:17:06', '2022-04-25 07:17:06', '<span style=\"font-family: \'Cambria\',serif;\">Any willful act of the Insured Person or his legal successor.</span>'),
(2, '2.2', '<span style=\"font-size: 11.0pt; line-height: 115%; font-family: \'Cambria\',serif;\">Người được bảo hiểm vi phạm nghi&ecirc;m trọng ph&aacute;p luật phải thụ &aacute;n h&igrave;nh sự v&agrave;/ hoặc vi phạm luật lệ an to&agrave;n giao th&ocirc;ng như đua xe, điều khiển xe, kh&ocirc;ng c&oacute; giấy ph&eacute;p l&aacute;i xe, đi v&agrave;o đường cấm, đường ngược chiều. </span>', 0, 16, 16, NULL, '2022-04-25 07:18:25', '2022-04-25 07:18:25', '<span style=\"font-family: \'Cambria\',serif;\">The Insured Person&rsquo;s severe violation of regulations and laws, for which he is subject to a criminal sentence or the Insured Person&rsquo;s violation of traffic regulations such as racing or driving without a valid driver\'s license or driving on restricted roads.</span>'),
(3, '2.3', '<span style=\"font-size: 11.0pt; line-height: 115%; font-family: \'Cambria\',serif;\">Hậu quả của việc uống rượu bia vượt qu&aacute; nồng độ theo quy định của luật giao th&ocirc;ng đường bộ hoặc c&aacute;c chất k&iacute;ch th&iacute;ch kh&aacute;c; người được bảo hiểm h&agrave;nh động dưới t&aacute;c động của thức uống c&oacute; cồn, thuốc k&iacute;ch th&iacute;ch, ma t&uacute;y đến mức mất khả năng kiểm so&aacute;t &yacute; thức; c&aacute;c bệnh được b&aacute;c sĩ ghi r&otilde; l&agrave; hậu quả của việc uống rượu, h&uacute;t thuốc hay sử dụng c&aacute;c chất k&iacute;ch th&iacute;ch kh&aacute;c.</span>', 0, 16, 16, NULL, '2022-04-25 07:18:54', '2022-04-25 07:18:54', '<span style=\"font-size: 11.0pt; line-height: 115%; font-family: \'Cambria\',serif;\">Any consequence of drinking alcohol or beer beyond the degree specified in the Law on Road Traffic Safety, or any other similar substance. The insured&rsquo;s act is impacted by alcohol drinkings, amphetamine, ecstacy, narcotic drugs to such extent that disable his/her consciousness control; any diseases clearly instructed by the physician as the consequences of drinking, smoking or using other amphetamine substances.</span>'),
(4, '2.4', '<span style=\"font-size: 11.0pt; line-height: 115%; font-family: \'Cambria\',serif;\">C&aacute;c h&agrave;nh động đ&aacute;nh nhau của người được bảo hiểm, trừ khi chứng minh được h&agrave;nh động đ&aacute;nh nhau đ&oacute; chỉ với mục đ&iacute;ch tự vệ.</span>', 0, 16, 17, NULL, '2022-04-25 07:19:22', '2022-04-27 08:52:25', '<span style=\"font-family: \'Cambria\',serif;\">The Insured&rsquo;s act of fighting, unless such act can be proved that it is only a defense against an attack.</span>'),
(5, '2.5', '<span style=\"font-size: 11.0pt; line-height: 115%; font-family: \'Cambria\',serif;\">Điều trị y tế hoặc sử dụng thuốc kh&ocirc;ng theo chỉ dẫn của b&aacute;c sĩ; điều trị thử nghiệm hoặc điều trị chưa được y học/ cơ quan y tế c&oacute; thẩm quyền c&ocirc;ng nhận.</span>', 0, 16, 16, NULL, '2022-04-25 07:19:53', '2022-04-25 07:19:53', '<span style=\"font-family: \'Cambria\',serif;\">Medical treatment or use of medications not as indicated by physicians; trial treatment or any kind of treatments that are not recognized by medical authority/medical science. </span>'),
(6, '2.6', '<span style=\"font-size: 11.0pt; line-height: 115%; font-family: \'Cambria\',serif;\">Tham gia c&aacute;c hoạt động h&agrave;ng kh&ocirc;ng, trừ khi với tư c&aacute;ch l&agrave; h&agrave;nh kh&aacute;ch; tham gia c&aacute;c cuộc diễn tập huấn luyện qu&acirc;n sự, tham gia chiến đấu của lực lượng vũ trang.</span>', 0, 16, 16, NULL, '2022-04-25 07:20:20', '2022-04-25 07:20:20', '<span style=\"font-size: 11.0pt; line-height: 115%; font-family: \'Cambria\',serif;\">The Insured Person&rsquo;s engagement in air transport activities other than as a fare-paying passenger; participation in maneuvers, military training, or army forces.</span>'),
(7, '2.7', '<span style=\"font-family: \'Cambria\',serif;\">Những rủi ro mang t&iacute;nh chất thảm họa như: động đất, n&uacute;i lửa, s&oacute;ng thần, nhiễm ph&oacute;ng xạ, dịch bệnh theo khuyến c&aacute;o của WHO từ cấp 6 trở l&ecirc;n.</span>', 0, 16, 16, NULL, '2022-04-25 07:20:45', '2022-04-25 07:20:45', '<span style=\"font-size: 11.0pt; line-height: 115%; font-family: \'Cambria\',serif;\">Catastrophic perils, such as earthquakes, volcanoes, tsunamis, radioactive contamination or pandemics graded Level 6 upwards by the WHO.</span>'),
(8, '2.8', '<span style=\"font-size: 11.0pt; line-height: 115%; font-family: \'Cambria\',serif;\">Chiến tranh, nội chiến, đ&igrave;nh c&ocirc;ng, khủng bố, bạo động d&acirc;n biến, phiến loạn c&aacute;c hoạt động d&acirc;n sự hoặc hoạt động của bất cứ người cầm đầu của tổ chức n&agrave;o nhằm lật đổ, đe dọa ch&iacute;nh quyền, kiểm so&aacute;t bằng vũ lực.</span>', 0, 16, 16, NULL, '2022-04-25 07:21:12', '2022-04-25 07:21:12', '<span style=\"font-size: 11.0pt; line-height: 115%; font-family: \'Cambria\',serif;\">War, civil war, strikes, terrorism, riots, civil commotion, rebellion, civil activities or actions the leader of any organization to overthrow or threaten the government or take control by force.</span>'),
(9, '2.9', '<span style=\"font-size: 11.0pt; line-height: 115%; font-family: \'Cambria\',serif;\">Tham gia tập luyện hoặc tham gia thi đấu c&aacute;c m&ocirc;n thể thao chuy&ecirc;n nghiệp, hoạt động thể thao mạo hiểm, nguy hiểm như săn bắn th&uacute;, trượt tuyết, trượt v&aacute;n tốc độ, leo n&uacute;i, lặn c&oacute; b&igrave;nh kh&iacute; n&eacute;n, l&aacute;i t&agrave;u lượn, nhảy d&ugrave;, nhảy bungee, lướt s&oacute;ng, bất kỳ hoạt động đua n&agrave;o (&aacute;p dụng cho mọi hoạt động hợp ph&aacute;p hay kh&ocirc;ng hợp ph&aacute;p, chuy&ecirc;n nghiệp hay nghiệp dư).</span>', 0, 16, 16, NULL, '2022-04-25 07:22:25', '2022-04-25 07:22:25', '<span style=\"font-family: \'Cambria\',serif;\">Participation in or training for any professional sports or any racing activity; hazardous, dangerous sport activities such as hunting, snow skiing, surfing, mount climbing, diving with cylinder, parachute jumping, glider hanging, bungee jumping, wave surfing or races of any other kinds (applied for all legal or illegal, professional or amateur activities). </span>'),
(10, '2.10', '<span style=\"font-size: 11.0pt; line-height: 115%; font-family: \'Cambria\',serif;\">Bệnh lao c&aacute;c loại, alzheimer, bệnh l&acirc;y lan qua đường t&igrave;nh dục, giang mai, bệnh lậu, hội chứng suy giảm miễn dịch (HIV) v&agrave; c&aacute;c hậu quả, biến chứng li&ecirc;n quan.</span>', 0, 16, 16, NULL, '2022-04-25 07:22:54', '2022-04-25 07:22:54', '<span style=\"font-family: \'Cambria\',serif;\">Treatment of tuberculosis of all kinds, alzheimer, sexually transmitted diseases, syphilis and gonorrhea and AIDS/HIV as well as all related illnesses, complications.</span>'),
(11, '2.11', '<span style=\"font-size: 11.0pt; line-height: 115%; font-family: \'Cambria\',serif;\">C&aacute;c bệnh di truyền, dị tật, khuyết tật bẩm sinh, bệnh dị dạng về gien. C&aacute;c loại bệnh do h&igrave;nh th&aacute;i cơ thể dị dạng sai kh&aacute;c với ti&ecirc;u chuẩn v&agrave; khuyết tật hoặc thiếu bộ phận do bẩm sinh v&agrave;/hoặc bệnh bẩm sinh. </span>', 0, 16, 16, NULL, '2022-04-25 07:23:25', '2022-04-25 07:23:25', '<span style=\"font-size: 11.0pt; line-height: 115%; font-family: \'Cambria\',serif;\">Hereditary diseases, deformities, birth defects or genetic malformations. Diseases caused by abnormal human body morphology and congenital defects or lack of body parts and/or congenital diseases. </span>'),
(12, '2.12', '<span style=\"font-size: 11.0pt; line-height: 115%; font-family: \'Cambria\',serif;\">Kiểm tra sức khỏe định kỳ (nội tr&uacute; hay ngoại tr&uacute;), gi&aacute;m định y khoa hoặc tư vấn y tế kh&ocirc;ng li&ecirc;n quan đến điều trị ốm đau hoặc thương tật, bao gồm cả kiểm tra phụ khoa/nam khoa. X&eacute;t nghiệm định kỳ cho trẻ mới sinh, tất cả c&aacute;c h&igrave;nh thức ti&ecirc;m chủng, vắc-xin v&agrave; thuốc ph&ograve;ng ngừa (trừ trường hợp ti&ecirc;m vắc &ndash;xin sau khi bị tai nạn&nbsp; hay s&uacute;c vật, c&ocirc;n tr&ugrave;ng cắn).</span>', 0, 16, 17, NULL, '2022-04-25 07:24:03', '2022-04-27 08:54:42', '<span style=\"font-family: \'Cambria\',serif;\">Periodic health examination (whether inpatient or outpatient); medical evaluation or consultation related to illness or injury treatment, including gynecological/andrological examination. Periodic tests, regular newborn screening, all forms of immunization, vaccination and preventive medication (except any vaccination due to an accident or animal or insect bites).</span>'),
(13, '2.13', '<span style=\"font-size: 11.0pt; line-height: 115%; font-family: \'Cambria\',serif;\">Mỏi mắt điều tiết, kh&ocirc; mắt. Kiểm tra thị lực, th&iacute;nh gi&aacute;c th&ocirc;ng thường. Điều trị suy biến tự nhi&ecirc;n về th&iacute;nh lực hay thị lực. C&aacute;c tật kh&uacute;c xạ như cận thị, viễn thị v&agrave; loạn thi v&agrave; bất kỳ phẫu thuật để phục hồi hiệu chỉnh n&agrave;o đối với c&aacute;c khuyết tật tho&aacute;i h&oacute;a th&iacute;nh gi&aacute;c v&agrave; thị gi&aacute;c. Đục thủy tinh thể của người tr&ecirc;n 55 tuổi v&agrave; suy giảm th&iacute;nh lực của người tr&ecirc;n 65 tuổi do mọi nguy&ecirc;n nh&acirc;n.</span>', 0, 16, 16, NULL, '2022-04-25 07:24:41', '2022-04-25 07:24:41', '<span style=\"font-family: \'Cambria\',serif;\">Dry eye syndrome, eyestrain. Normal eyesight and hearing tests. Treatment of natural degeneration on hearing or eyesight. Other refractive defects such as nearsightedness, farsightedness and astigmatism and any surgical operations to recover or correct eyesight and hearing degeneration. Catarac surgery/treatment at people of over 55 years of age and gradual hearing loss at people of over 65 years of age, regardless of any causes.</span>'),
(14, '2.14', '<span style=\"font-family: \'Cambria\',serif;\">Điều trị hoặc phẫu thuật theo y&ecirc;u cầu của người được bảo hiểm m&agrave; kh&ocirc;ng phải điều trị theo c&aacute;ch th&ocirc;ng thường; dịch vụ y tế kh&ocirc;ng cần thiết hoặc chi ph&iacute; y tế vượt mức chi ph&iacute; hợp l&yacute;. Những chỉ định phẫu thuật c&oacute; từ trước ng&agrave;y bắt đầu bảo hiểm.</span>', 0, 16, 16, NULL, '2022-04-25 07:25:10', '2022-04-25 07:25:10', '<span style=\"font-size: 11.0pt; line-height: 115%; font-family: \'Cambria\',serif;\">Any treatment or surgery, at the request of the Insured Person which is not conducted in an ordinary manners; unnecessary medical services or unreasonably excessive charges. Any surgery which has been prescribed/instructed before the inception date. </span>'),
(15, '2.15', '<span style=\"font-size: 11.0pt; line-height: 115%; font-family: \'Cambria\',serif;\">Phẫu thuật thẩm mỹ, chỉnh h&igrave;nh thẩm mỹ; c&aacute;c điều trị mang t&iacute;nh chất thẩm mỹ kể cả việc giải phẫu thẩm mỹ n&agrave;y nhằm mục đ&iacute;ch t&aacute;i tạo để phục hồi chức năng của cơ quan bị tổn thương ph&aacute;t sinh trong thời hạn bảo hiểm.</span>', 0, 16, 16, NULL, '2022-04-25 07:25:38', '2022-04-25 07:25:38', '<span style=\"font-size: 11.0pt; line-height: 115%; font-family: \'Cambria\',serif;\">Cosmetic surgery, aesthetic orthopaedy; any cosmetic treatment, regardless of the purpose for the surgery as to restructure damaged bodily organs due to injury incurred during insurance period.</span>'),
(16, '2.16', '<span style=\"font-family: \'Cambria\',serif;\">Mụn c&aacute;c loại (bao gồm mụn cơm, mụn c&oacute;c), trứng c&aacute;, vi&ecirc;m da dầu; rụng t&oacute;c do mọi nguy&ecirc;n nh&acirc;n, điều trị tăng sắc tố (n&aacute;m da), vv &hellip;bị loại trừ ri&ecirc;ng đối với điều kiện ngoại tr&uacute;.</span>', 0, 16, 16, NULL, '2022-04-25 07:26:15', '2022-04-25 07:26:15', '<span style=\"font-family: \'Cambria\',serif;\">Pimples of all kinds (including warts and verrucas), acnes, seborrheic dermatitis; alopecia due to any reasons, hyperpigmentation (melasma skin) treatment, etc. are particularly excluded from the outpatient treatment benefit.</span>'),
(17, '2.17', '<span style=\"font-family: \'Cambria\',serif;\">Chi ph&iacute; để sử dụng, cung cấp, bảo dưỡng, sửa chữa hay thay thế bộ phận giả hay thiết bị, dụng cụ y tế theo định nghĩa ở mục số 35. Tuy nhi&ecirc;n, ri&ecirc;ng đối với phần sử dụng đĩa đệm, nẹp, vis cố định v&agrave;o cơ thể được chi trả &aacute;p dụng như sau:</span><br />\r\n<ul>\r\n<li><span style=\"font-family: \'Cambria\',serif;\">Đối với điều trị bệnh cơ xương khớp: loại trừ đối với cả điều kiện D v&agrave; ngoại tr&uacute;;</span></li>\r\n<li><span style=\"font-size: 11.0pt; line-height: 115%; font-family: \'Cambria\',serif;\">Đối với trường hợp tai nạn: &aacute;p dụng giới hạn 10% STBH của chi ph&iacute; y tế do tai nạn.</span></li>\r\n</ul>', 0, 16, 16, NULL, '2022-04-25 08:22:31', '2022-04-25 08:22:31', '<span style=\"font-family: \'Cambria\',serif;\">Costs of providing, maintaining, repairing or replacing prostheses or equipment and devices as defined in Definition 35. However, the use of discs, splints and screws is excluded as follows:</span><br />\r\n<ul>\r\n<li><span style=\"font-family: \'Cambria\',serif;\">In case of treatment of musculoskeletal diseases: This exclusion applies to Condition D and outpatient treatment.</span></li>\r\n<li><span style=\"font-size: 11.0pt; line-height: 115%; font-family: \'Cambria\',serif;\">In case of an accident: 10% of the Sum Insured for medical expenses following an accident shall be applied.</span></li>\r\n</ul>'),
(18, '2.18', '<span style=\"font-family: \'Cambria\',serif;\">Thực phẩm chức năng. C&aacute;c chất bổ sung hoặc thay thế phục vụ cho việc ăn ki&ecirc;ng c&oacute; sẵn trong tự nhi&ecirc;n v&agrave; c&oacute; thể được mua m&agrave; kh&ocirc;ng cần chỉ định; c&aacute;c loại vitamin, thuốc bổ, kho&aacute;ng chất v&agrave; c&aacute;c chất hữu cơ (trừ trường hợp c&aacute;c loại vitamin li&ecirc;n quan đến bệnh, c&oacute; chỉ định của b&aacute;c sĩ v&agrave; chi ph&iacute; vitamin kh&ocirc;ng lớn hơn chi ph&iacute; thuốc điều trị).</span>', 0, 16, 16, NULL, '2022-04-25 08:23:06', '2022-04-25 08:23:06', '<span style=\"font-size: 11.0pt; line-height: 115%; font-family: \'Cambria\',serif; color: black;\">Functional food. Dietary supplements or substitutes, which are naturally available or can be purchased without prescription; all kinds of vitamins, minerals and organic substances (except for those vitamins prescribed by a Physician at the cost that is not greater than that of treatment medicine).</span>'),
(19, '2.19', '<span style=\"font-family: \'Cambria\',serif;\">Thực hiện c&aacute;c biện ph&aacute;p kế hoạch h&oacute;a gia đ&igrave;nh, hậu quả của ph&aacute; thai do t&acirc;m l&yacute; hay x&atilde; hội, điều trị v&ocirc; sinh nam/nữ, thụ tinh nh&acirc;n tạo, điều trị bất lực, thiếu hooc m&ocirc;n sinh trưởng, rối loạn chức năng sinh dục (mộng tinh, xuất tinh sớm, xuất tinh ngược d&ograve;ng, ...) hay thay đổi giới t&iacute;nh v&agrave; bất cứ hậu quả n&agrave;o hay biến chứng n&agrave;o từ những điều kiện tr&ecirc;n. </span>', 0, 16, 16, NULL, '2022-04-25 08:23:47', '2022-04-25 08:23:47', '<span style=\"font-family: \'Cambria\',serif; color: black;\">Family planning measures, consequences of abortion due to psychological or social causes, male/female infertility treatment, artificial reproductive techniques, impotence treatment, growth hormone deficiency, sexual dysfunction (nocturnal emission</span>, <span style=\"font-family: \'Cambria\',serif; color: black;\">premature ejaculation, retrograde ejaculation, ...) or gender transformation, and any consequences or complications thereof.</span>'),
(20, '2.20', '<span style=\"font-family: \'Cambria\',serif;\">C&ograve;i xương, suy dinh dưỡng, điều trị kiểm so&aacute;t trọng lượng cơ thể (tăng hoặc giảm c&acirc;n).</span>', 0, 16, 16, NULL, '2022-04-25 08:24:15', '2022-04-25 08:24:15', '<span style=\"font-family: \'Cambria\',serif; color: black;\">Rickety, malnutrition, body weight control (weight gain or loss treatment).</span>'),
(21, '2.21', '<span style=\"font-size: 11.0pt; line-height: 115%; font-family: \'Cambria\',serif;\">Điều trị bệnh t&acirc;m thần, rối loạn t&acirc;m thần, động kinh&hellip;Điều trị rối loạn giấc ngủ, mất ngủ, suy nhược v&agrave; hội chứng căng thẳng do c&ocirc;ng việc (stress) v&agrave; c&aacute;c bệnh li&ecirc;n quan đến hội chứng đ&oacute;.</span>', 0, 16, 16, NULL, '2022-04-25 08:24:45', '2022-04-25 08:24:45', '<span style=\"font-family: \'Cambria\',serif; color: black;\">Treatment of mental illness; psychiatric disorders or epilepsy. Treatment of sleep disorders, insomnia, depression and work-related stress syndrome and diseases related to such syndrome.</span>'),
(22, '2.22', '<span style=\"font-family: \'Cambria\',serif;\">Điều trị tại ph&ograve;ng mạch b&aacute;c sĩ tư, ph&ograve;ng nha tư nh&acirc;n kh&ocirc;ng c&oacute; giấy ph&eacute;p h&agrave;nh nghề v&agrave; kh&ocirc;ng cung cấp được chứng từ/h&oacute;a đơn t&agrave;i ch&iacute;nh theo quy định của luật ph&aacute;p trừ trường hợp c&oacute; quy định kh&aacute;c được ghi r&otilde; trong Đơn/Hợp đồng bảo hiểm hoặc Sửa đổi bổ sung.</span>', 0, 16, 16, NULL, '2022-04-25 08:25:11', '2022-04-25 08:25:11', '<span style=\"font-size: 11.0pt; line-height: 115%; font-family: \'Cambria\',serif;\">Treatment at a private clinic or dental clinic, which is unlicensed or fails to provide receipts/invoices in accordance with legal regulations, unless otherwise specified in the Schedule or any Endorsement. </span>'),
(23, '2.23', '<span style=\"font-family: \'Cambria\',serif;\">Kh&aacute;m bệnh kh&ocirc;ng theo đ&uacute;ng quy tr&igrave;nh kh&aacute;m chữa bệnh của cơ sở y tế như kh&ocirc;ng đ&oacute;ng tiền kh&aacute;m, kh&ocirc;ng c&oacute; t&ecirc;n trong sổ lưu bệnh, vv</span>', 0, 16, 16, NULL, '2022-04-25 08:25:41', '2022-04-25 08:25:41', '<span style=\"font-size: 11.0pt; line-height: 115%; font-family: \'Cambria\',serif;\">Medical examination is executed at a non compliance procedure according to standard of that medical facility such as failure to pay examination expenses, names unlisted in the hospital recording book, etc.</span>'),
(24, '2.24', '<span style=\"font-family: \'Cambria\',serif;\">C&aacute;c chi ph&iacute; li&ecirc;n quan đến thai sản v&agrave; sinh đẻ trừ khi c&oacute; thỏa thuận kh&aacute;c. C&aacute;c biến chứng thai sản ph&aacute;t sinh tr&ecirc;n người thụ tinh nh&acirc;n tạo (IVF, IUI) v&agrave; người mang thai hộ; thủ thuật mở th&ocirc;ng buồng trứng, nhập viện theo d&otilde;i thai trước khi sinh chuyển dạ giả (Braxton hicks).</span>', 0, 16, 16, NULL, '2022-04-25 08:26:13', '2022-04-25 08:26:13', '<span style=\"font-family: \'Cambria\',serif;\">Pregnancy and delivery related costs and expenses, unless otherwise specified. Pregnancy complications upon the insured who has undergone infertility treatment (IVF, IUI) and surrogate mother; oophorostomy, hospitalization due to false labor (Braxton hicks).</span>'),
(25, '2.25', '<span style=\"font-size: 11.0pt; line-height: 115%; font-family: \'Cambria\',serif;\">Bệnh đặc biệt v&agrave; bệnh/thương tật c&oacute; sẵn trong năm đầu ti&ecirc;n của Đơn/Hợp đồng bảo hiểm, trừ khi c&oacute; thỏa thuận kh&aacute;c.</span>', 0, 16, 16, NULL, '2022-04-25 08:26:41', '2022-04-25 08:26:41', '<span style=\"font-family: \'Cambria\',serif;\">Any special or pre-existing illness and disease in the first policy year unless otherwise agreed.</span>'),
(26, '2.26', '<span style=\"font-size: 11.0pt; line-height: 115%; font-family: \'Cambria\',serif;\">Bệnh nghề nghiệp trừ khi c&oacute; thỏa thuận kh&aacute;c.</span>', 0, 16, 16, NULL, '2022-04-25 08:27:08', '2022-04-25 08:27:08', '<span style=\"font-family: \'Cambria\',serif;\">Occupational diseases, unless otherwise agreed.</span>'),
(27, '2.27', '<span style=\"font-size: 11.0pt; line-height: 115%; font-family: \'Cambria\',serif;\">C&aacute;c kh&aacute;ng nguy&ecirc;n điều trị; c&aacute;c thuốc mang t&iacute;nh chất dự ph&ograve;ng v&agrave; tăng cường hệ miễn dịch, tăng cường sức đề kh&aacute;ng (pediakid immune, broncho vacxom, vacunace, vvv) bao gồm nhưng kh&ocirc;ng giới hạn bởi c&aacute;c thuốc chứa hoạt chất Gamma Globulin (IGIM), hoạt chất Glutathione.</span>', 0, 16, 16, NULL, '2022-04-25 08:27:38', '2022-04-25 08:27:38', '<span style=\"font-family: \'Cambria\',serif;\">Antigen for treatment; prevention related medicine and immune enforcement related medicine (pediakid immune, broncho vacxom, vacunace, etc), including but not limited to drugs containing such active element as Gamma Globulin (IGIM), Glutathione</span>'),
(28, '2.28', '<span style=\"font-family: \'Cambria\',serif;\">C&aacute;c chế phẩm nước muối biển; nước mắt nh&acirc;n tạo; c&aacute;c chế phẩm men ti&ecirc;u h&oacute;a v&agrave; chế phẩm Đ&ocirc;ng Y kh&ocirc;ng c&oacute; số đăng k&yacute; dược phẩm cấp bởi Bộ Y tế m&agrave; chỉ c&oacute; số đăng k&yacute; ti&ecirc;u chuẩn cơ sở.</span>', 0, 16, 16, NULL, '2022-04-25 08:28:04', '2022-04-25 08:28:04', '<span style=\"font-family: \'Cambria\',serif;\">Sea water; artificial eyedrops; digestive enzymes and traditional herbal products which are registed under facilty standard code without pharmaceutical code granted by Ministry of Health.</span>'),
(29, '2.29', '<span style=\"font-family: \'Cambria\',serif;\">Nhổ, phẫu thuật, điều trị răng nội tr&uacute;.</span>', 0, 16, 16, NULL, '2022-04-25 08:28:29', '2022-04-25 08:28:29', '<span style=\"font-family: \'Cambria\',serif;\">Inpatient dental treatment and surgery.</span>'),
(30, '2.30', '<span style=\"font-family: \'Cambria\',serif;\">C&aacute;c chẩn đo&aacute;n, phẫu thuật, điều trị li&ecirc;n quan đến hooc m&ocirc;n v&agrave; tế b&agrave;o gốc.</span>', 0, 16, 16, NULL, '2022-04-25 08:29:01', '2022-04-25 08:29:01', '<span style=\"font-family: \'Cambria\',serif;\">Diagnostics, surgery, treatment relating to hormones and stem cell therapy.</span>'),
(31, '2.31', '<span style=\"font-family: \'Cambria\',serif;\">C&aacute;c chứng bệnh li&ecirc;n quan đến việc trở ngại đường h&ocirc; hấp, bao gồm ngủ ng&aacute;y v&agrave; ngưng thở khi ngủ.</span>', 0, 16, 16, NULL, '2022-04-25 08:29:26', '2022-04-25 08:29:26', '<span style=\"font-family: \'Cambria\',serif;\">Diseases relating to aspiratory obstacles such as snoring and sleep apnea.</span>'),
(32, '2.32', '<span style=\"font-size: 11.0pt; line-height: 115%; font-family: \'Cambria\',serif;\">Mọi chi ph&iacute; chẩn đo&aacute;n, điều trị v&agrave; phẫu thuật nối d&acirc;y g&acirc;n/d&acirc;y chằng trong năm đầu ti&ecirc;n (loại trừ với mọi điều kiện, mọi nguy&ecirc;n nh&acirc;n).</span>', 0, 16, 16, NULL, '2022-04-25 08:29:57', '2022-04-25 08:29:57', '<span style=\"font-family: \'Cambria\',serif;\">All expenses relating to diagnosis, treatment and surgery of tendon during the first policy year (excluded with all reasons, all conditions).</span>'),
(33, '2.33', '<span style=\"font-family: \'Cambria\',serif;\">C&aacute;c spa, c&aacute;c trung t&acirc;m vật l&yacute; trị liệu v&agrave; phục hồi chức năng tư nh&acirc;n; c&aacute;c ph&ograve;ng kh&aacute;m y tế thuộc nh&agrave; m&aacute;y/ c&ocirc;ng trường/trường học.</span>', 0, 16, 16, NULL, '2022-04-25 08:30:32', '2022-04-25 08:30:32', '<span style=\"font-size: 11.0pt; line-height: 115%; font-family: \'Cambria\',serif;\">Spa, private rehabilitation and physiotherapy, medical center of the factory, worksite, school.</span>'),
(34, '2.34', '<span style=\"font-family: \'Cambria\',serif;\">Tự tử; chết kh&ocirc;ng r&otilde; nguy&ecirc;n nh&acirc;n.</span>', 0, 16, 16, NULL, '2022-04-25 08:31:17', '2022-04-25 08:31:17', '<span style=\"font-family: \'Cambria\',serif;\">Suicide; death due to unknow reasons/causes.</span>'),
(35, '2.35', '<span style=\"font-size: 11.0pt; line-height: 115%; font-family: \'Cambria\',serif;\">Người được bảo hiểm vắng mặt ở Việt Nam hơn 180 ng&agrave;y trong suốt thời hạn bảo hiểm trừ khi c&oacute; C&ocirc;ng ty bảo hiểm đồng &yacute; bảo hiểm cho sự vắng mặt đ&oacute; v&agrave; ph&iacute; bổ sung sẽ được &aacute;p dụng.</span>', 0, 16, 16, NULL, '2022-04-25 08:31:40', '2022-04-25 08:31:40', '<span style=\"font-size: 11.0pt; line-height: 115%; font-family: \'Cambria\',serif;\">The insured does not reside in Vietnam for more than 180 days per one policy period unless accepted by the Insurance Company provided that additional premiums shall be applied. </span>'),
(36, '2.1 (Exclusions CPH)', '<span style=\"font-family: \'Cambria\',serif;\">Any willful act of the Insured Person or his legal successor.</span>', 1, 17, 17, '2022-04-27 09:13:11', '2022-04-27 09:02:04', '2022-04-27 09:13:11', NULL),
(37, '2.2 (Exclusions CPH)', '<span style=\"font-family: \'Cambria\',serif;\">The Insured Person&rsquo;s severe violation of regulations and laws, for which he is subject to a criminal sentence or the Insured Person&rsquo;s violation of traffic regulations such as racing or driving without a valid driver\'s license or driving on restricted roads.</span>', 1, 17, 17, '2022-04-27 09:15:13', '2022-04-27 09:04:10', '2022-04-27 09:15:13', NULL),
(38, '2.3 (Exclusions CPH)', '<span style=\"font-family: \'Cambria\',serif;\">Any consequence of drinking alcohol or beer beyond the degree specified in the Law on Road Traffic Safety, or any other similar substance. The insured&rsquo;s act is impacted by alcohol drinkings, amphetamine, ecstacy, narcotic drugs to such extent that disable his/her consciousness control; any diseases clearly instructed by the physician as the consequences of drinking, smoking or using other amphetamine substances.</span>', 1, 17, 17, '2022-04-27 09:15:38', '2022-04-27 09:05:44', '2022-04-27 09:15:38', NULL),
(39, '2.4 (Exclusions CPH)', '<span style=\"font-family: \'Cambria\',serif;\">The Insured&rsquo;s act of fighting, unless such act can be proved that it is only a defense against an attack.</span>', 1, 17, 17, '2022-04-27 09:15:30', '2022-04-27 09:06:11', '2022-04-27 09:15:30', NULL),
(40, '2.5 (Exclusions CPH)', '<span style=\"font-family: \'Cambria\',serif;\">Medical treatment or use of medications not as indicated by physicians; trial treatment or any kind of treatments that are not recognized by medical authority/medical science. </span>', 1, 17, 17, '2022-04-27 09:15:23', '2022-04-27 09:06:33', '2022-04-27 09:15:23', NULL),
(41, '2.6 (Exclusions CPH)', '<span style=\"font-family: \'Cambria\',serif;\">The Insured Person&rsquo;s engagement in air transport activities other than as a fare-paying passenger; participation in maneuvers, military training, or army forces.</span>', 1, 17, 17, '2022-04-27 09:15:19', '2022-04-27 09:06:58', '2022-04-27 09:15:19', NULL);

--
-- Indexes for dumped tables
--

--
-- Indexes for table `terms`
--
ALTER TABLE `terms`
  ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `terms`
--
ALTER TABLE `terms`
  MODIFY `id` bigint(20) UNSIGNED NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=42;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
